nodeLinker: node-modules
enableGlobalCache: true

npmRegistryServer: 'https://registry.npmjs.org/'
enableStrictSsl: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-berry.cjs
