services:
  api-dev:
    build:
      context: .
      target: dev
    ports: ['3000:3010']
    env_file: .env
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules

  api:
    build:
      context: .
      target: prod
    ports: ['3000:3010']
    env_file: .env
    restart: unless-stopped

volumes:
  app_node_modules: {}
