services:
  api-dev:
    build:
      context: .
      target: dev
    ports: ['3000:3010']
    environment:
      - PORT=3010
      - NODE_ENV=development
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules

  api:
    build:
      context: .
      target: prod
    environment:
      - PORT=3010
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  app_node_modules: {}
