services:
  api-dev:
    build:
      context: .
      target: dev
    ports: ['3000:3010']
    env_file: .env
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./.env:/app/.env

  api:
    build:
      context: .
      target: prod
    ports: ['3000:3010']
    env_file: .env
    restart: unless-stopped

volumes:
  app_node_modules: {}
