name: Deploy com Coolify

on:
  workflow_run:
    workflows: ['Continuous Integration']
    branches: [main]
    types:
      - completed

concurrency:
  group: coolify-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy no Coolify
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Aguardar disponibilidade da imagem (curto)
        run: sleep 10
      - name: Acionar deploy no Coolify
        env:
          COOLIFY_WEBHOOK: ${{ secrets.COOLIFY_WEBHOOK }}
          COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}
        run: |
          set -euo pipefail
          if [ -z "${COOLIFY_WEBHOOK:-}" ]; then
            echo "COOLIFY_WEBHOOK não configurado" >&2
            exit 1
          fi
          # Usar método GET conforme documentação oficial do Coolify
          if [ -n "${COOLIFY_TOKEN:-}" ]; then
            curl -sS -X GET "$COOLIFY_WEBHOOK" \
              -H "Authorization: Bearer $COOLIFY_TOKEN" \
              --fail-with-body
          else
            curl -sS -X GET "$COOLIFY_WEBHOOK" --fail-with-body
          fi
