name: Deploy com Coolify

on:
  workflow_run:
    workflows: ['Continuous Integration']
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    name: Deploy no Coolify
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Acionar deploy no Coolify
        run: |
          curl --request GET "${{ secrets.COOLIFY_WEBHOOK }}" \
               --header "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"
