name: Deploy com Coolify

on:
  workflow_run:
    workflows: ['Continuous Integration']
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    name: Deploy no Coolify
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Acionar deploy no Coolify
        env:
          COOLIFY_WEBHOOK: ${{ secrets.COOLIFY_WEBHOOK }}
          COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}
        run: |
          set -euo pipefail
          if [ -z "${COOLIFY_WEBHOOK:-}" ]; then
            echo "COOLIFY_WEBHOOK não configurado" >&2
            exit 1
          fi
          # Use POST e anexe o header Authorization apenas se houver token
          if [ -n "${COOLIFY_TOKEN:-}" ]; then
            curl -sS -X POST "$COOLIFY_WEBHOOK" \
              -H "Authorization: Bearer $COOLIFY_TOKEN" \
              --fail-with-body
          else
            curl -sS -X POST "$COOLIFY_WEBHOOK" --fail-with-body
          fi
